package com.example.admin.tombola;


import android.content.res.Resources;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.ColorFilter;
import android.graphics.PorterDuff;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.LayerDrawable;
import android.graphics.drawable.ScaleDrawable;
import android.graphics.drawable.shapes.RectShape;
import android.graphics.drawable.shapes.Shape;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.TextView;
import java.util.ArrayList;

public class ActivityMain  extends AppCompatActivity {

    private ArrayList<ImageButton> caselle;
    private ImageButton cinquina;
    private ImageButton decima;
    private ImageButton tombola;
    private TextView ultimo;
    private TextView penultimo;
    private TextView terzultimo;
    private TextView giro;

    public TextView getUltimo() { return ultimo;}

    public TextView getPenultimo() { return penultimo; }

    public TextView getTerzultimo() { return terzultimo; }

    public TextView getGiro() { return giro; }

    public ArrayList<ImageButton> getCaselle() { return caselle; }

    public ImageButton getCinquina() {
        return cinquina;
    }

    public ImageButton getDecima() {
        return decima;
    }

    public ImageButton getTombola() {
        return tombola;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ultimo = (TextView)findViewById(R.id.ultimo_numero);
        penultimo = (TextView)findViewById(R.id.penultimo_numero);
        terzultimo = (TextView)findViewById(R.id.terzultimo_numero);
        giro = (TextView)findViewById(R.id.giro);
        ImageButton piu = (ImageButton) findViewById(R.id.piu);
        ImageButton meno = (ImageButton) findViewById(R.id.meno);
        ImageButton annulla = (ImageButton) findViewById(R.id.annulla);
        cinquina =(ImageButton)findViewById(R.id.cinquina);
        decima =(ImageButton)findViewById(R.id.decima);
        tombola =(ImageButton)findViewById(R.id.tombola);
        caselle = new ArrayList<>(90);
        AscoltatoreActivityMain ascoltatore = new AscoltatoreActivityMain(this);
        Button casella0 = (Button) findViewById(R.id.casella0);
        casella0.setOnClickListener(ascoltatore);
        ImageButton casella1 = (ImageButton)findViewById(R.id.casella1);
        casella1.setOnClickListener(ascoltatore);
        caselle.add(casella1);
        ImageButton casella2 = (ImageButton)findViewById(R.id.casella2);
        casella2.setOnClickListener(ascoltatore);
        caselle.add(casella2);
        ImageButton casella3 = (ImageButton)findViewById(R.id.casella3);
        casella3.setOnClickListener(ascoltatore);
        caselle.add(casella3);
        ImageButton casella4 = (ImageButton)findViewById(R.id.casella4);
        casella4.setOnClickListener(ascoltatore);
        caselle.add(casella4);
        ImageButton casella5 = (ImageButton)findViewById(R.id.casella5);
        casella5.setOnClickListener(ascoltatore);
        caselle.add(casella5);
        ImageButton casella6 = (ImageButton)findViewById(R.id.casella6);
        casella6.setOnClickListener(ascoltatore);
        caselle.add(casella6);
        ImageButton casella7 = (ImageButton)findViewById(R.id.casella7);
        casella7.setOnClickListener(ascoltatore);
        caselle.add(casella7);
        ImageButton casella8 = (ImageButton)findViewById(R.id.casella8);
        casella8.setOnClickListener(ascoltatore);
        caselle.add(casella8);
        ImageButton casella9 = (ImageButton)findViewById(R.id.casella9);
        casella9.setOnClickListener(ascoltatore);
        caselle.add(casella9);
        ImageButton casella10 = (ImageButton)findViewById(R.id.casella10);
        casella10.setOnClickListener(ascoltatore);
        caselle.add(casella10);
        ImageButton casella11 = (ImageButton)findViewById(R.id.casella11);
        casella11.setOnClickListener(ascoltatore);
        caselle.add(casella11);
        ImageButton casella12 = (ImageButton)findViewById(R.id.casella12);
        casella12.setOnClickListener(ascoltatore);
        caselle.add(casella12);
        ImageButton casella13 = (ImageButton)findViewById(R.id.casella13);
        casella13.setOnClickListener(ascoltatore);
        caselle.add(casella13);
        ImageButton casella14 = (ImageButton)findViewById(R.id.casella14);
        casella14.setOnClickListener(ascoltatore);
        caselle.add(casella14);
        ImageButton casella15 = (ImageButton)findViewById(R.id.casella15);
        casella15.setOnClickListener(ascoltatore);
        caselle.add(casella15);
        ImageButton casella16 = (ImageButton)findViewById(R.id.casella16);
        casella16.setOnClickListener(ascoltatore);
        caselle.add(casella16);
        ImageButton casella17 = (ImageButton)findViewById(R.id.casella17);
        casella17.setOnClickListener(ascoltatore);
        caselle.add(casella17);
        ImageButton casella18 = (ImageButton)findViewById(R.id.casella18);
        casella18.setOnClickListener(ascoltatore);
        caselle.add(casella18);
        ImageButton casella19 = (ImageButton)findViewById(R.id.casella19);
        casella19.setOnClickListener(ascoltatore);
        caselle.add(casella19);
        ImageButton casella20 = (ImageButton)findViewById(R.id.casella20);
        casella20.setOnClickListener(ascoltatore);
        caselle.add(casella20);
        ImageButton casella21 = (ImageButton)findViewById(R.id.casella21);
        casella21.setOnClickListener(ascoltatore);
        caselle.add(casella21);
        ImageButton casella22 = (ImageButton)findViewById(R.id.casella22);
        casella22.setOnClickListener(ascoltatore);
        caselle.add(casella22);
        ImageButton casella23 = (ImageButton)findViewById(R.id.casella23);
        casella23.setOnClickListener(ascoltatore);
        caselle.add(casella23);
        ImageButton casella24 = (ImageButton)findViewById(R.id.casella24);
        casella24.setOnClickListener(ascoltatore);
        caselle.add(casella24);
        ImageButton casella25 = (ImageButton)findViewById(R.id.casella25);
        casella25.setOnClickListener(ascoltatore);
        caselle.add(casella25);
        ImageButton casella26 = (ImageButton)findViewById(R.id.casella26);
        casella26.setOnClickListener(ascoltatore);
        caselle.add(casella26);
        ImageButton casella27 = (ImageButton)findViewById(R.id.casella27);
        casella27.setOnClickListener(ascoltatore);
        caselle.add(casella27);
        ImageButton casella28 = (ImageButton)findViewById(R.id.casella28);
        casella28.setOnClickListener(ascoltatore);
        caselle.add(casella28);
        ImageButton casella29 = (ImageButton)findViewById(R.id.casella29);
        casella29.setOnClickListener(ascoltatore);
        caselle.add(casella29);
        ImageButton casella30 = (ImageButton)findViewById(R.id.casella30);
        casella30.setOnClickListener(ascoltatore);
        caselle.add(casella30);
        ImageButton casella31 = (ImageButton)findViewById(R.id.casella31);
        casella31.setOnClickListener(ascoltatore);
        caselle.add(casella31);
        ImageButton casella32 = (ImageButton)findViewById(R.id.casella32);
        casella32.setOnClickListener(ascoltatore);
        caselle.add(casella32);
        ImageButton casella33 = (ImageButton)findViewById(R.id.casella33);
        casella33.setOnClickListener(ascoltatore);
        caselle.add(casella33);
        ImageButton casella34 = (ImageButton)findViewById(R.id.casella34);
        casella34.setOnClickListener(ascoltatore);
        caselle.add(casella34);
        ImageButton casella35 = (ImageButton)findViewById(R.id.casella35);
        casella35.setOnClickListener(ascoltatore);
        caselle.add(casella35);
        ImageButton casella36 = (ImageButton)findViewById(R.id.casella36);
        casella36.setOnClickListener(ascoltatore);
        caselle.add(casella36);
        ImageButton casella37 = (ImageButton)findViewById(R.id.casella37);
        casella37.setOnClickListener(ascoltatore);
        caselle.add(casella37);
        ImageButton casella38 = (ImageButton)findViewById(R.id.casella38);
        casella38.setOnClickListener(ascoltatore);
        caselle.add(casella38);
        ImageButton casella39 = (ImageButton)findViewById(R.id.casella39);
        casella39.setOnClickListener(ascoltatore);
        caselle.add(casella39);
        ImageButton casella40 = (ImageButton)findViewById(R.id.casella40);
        casella40.setOnClickListener(ascoltatore);
        caselle.add(casella40);
        ImageButton casella41 = (ImageButton)findViewById(R.id.casella41);
        casella41.setOnClickListener(ascoltatore);
        caselle.add(casella41);
        ImageButton casella42 = (ImageButton)findViewById(R.id.casella42);
        casella42.setOnClickListener(ascoltatore);
        caselle.add(casella42);
        ImageButton casella43 = (ImageButton)findViewById(R.id.casella43);
        casella43.setOnClickListener(ascoltatore);
        caselle.add(casella43);
        ImageButton casella44 = (ImageButton)findViewById(R.id.casella44);
        casella44.setOnClickListener(ascoltatore);
        caselle.add(casella44);
        ImageButton casella45 = (ImageButton)findViewById(R.id.casella45);
        casella45.setOnClickListener(ascoltatore);
        caselle.add(casella45);
        ImageButton casella46 = (ImageButton)findViewById(R.id.casella46);
        casella46.setOnClickListener(ascoltatore);
        caselle.add(casella46);
        ImageButton casella47 = (ImageButton)findViewById(R.id.casella47);
        casella47.setOnClickListener(ascoltatore);
        caselle.add(casella47);
        ImageButton casella48 = (ImageButton)findViewById(R.id.casella48);
        casella48.setOnClickListener(ascoltatore);
        caselle.add(casella48);
        ImageButton casella49 = (ImageButton)findViewById(R.id.casella49);
        casella49.setOnClickListener(ascoltatore);
        caselle.add(casella49);
        ImageButton casella50 = (ImageButton)findViewById(R.id.casella50);
        casella50.setOnClickListener(ascoltatore);
        caselle.add(casella50);
        ImageButton casella51 = (ImageButton)findViewById(R.id.casella51);
        casella51.setOnClickListener(ascoltatore);
        caselle.add(casella51);
        ImageButton casella52 = (ImageButton)findViewById(R.id.casella52);
        casella52.setOnClickListener(ascoltatore);
        caselle.add(casella52);
        ImageButton casella53 = (ImageButton)findViewById(R.id.casella53);
        casella53.setOnClickListener(ascoltatore);
        caselle.add(casella53);
        ImageButton casella54 = (ImageButton)findViewById(R.id.casella54);
        casella54.setOnClickListener(ascoltatore);
        caselle.add(casella54);
        ImageButton casella55 = (ImageButton)findViewById(R.id.casella55);
        casella55.setOnClickListener(ascoltatore);
        caselle.add(casella55);
        ImageButton casella56 = (ImageButton)findViewById(R.id.casella56);
        casella56.setOnClickListener(ascoltatore);
        caselle.add(casella56);
        ImageButton casella57 = (ImageButton)findViewById(R.id.casella57);
        casella57.setOnClickListener(ascoltatore);
        caselle.add(casella57);
        ImageButton casella58 = (ImageButton)findViewById(R.id.casella58);
        casella58.setOnClickListener(ascoltatore);
        caselle.add(casella58);
        ImageButton casella59 = (ImageButton)findViewById(R.id.casella59);
        casella59.setOnClickListener(ascoltatore);
        caselle.add(casella59);
        ImageButton casella60 = (ImageButton)findViewById(R.id.casella60);
        casella60.setOnClickListener(ascoltatore);
        caselle.add(casella60);
        ImageButton casella61 = (ImageButton)findViewById(R.id.casella61);
        casella61.setOnClickListener(ascoltatore);
        caselle.add(casella61);
        ImageButton casella62 = (ImageButton)findViewById(R.id.casella62);
        casella62.setOnClickListener(ascoltatore);
        caselle.add(casella62);
        ImageButton casella63 = (ImageButton)findViewById(R.id.casella63);
        casella63.setOnClickListener(ascoltatore);
        caselle.add(casella63);
        ImageButton casella64 = (ImageButton)findViewById(R.id.casella64);
        casella64.setOnClickListener(ascoltatore);
        caselle.add(casella64);
        ImageButton casella65 = (ImageButton)findViewById(R.id.casella65);
        casella65.setOnClickListener(ascoltatore);
        caselle.add(casella65);
        ImageButton casella66 = (ImageButton)findViewById(R.id.casella66);
        casella66.setOnClickListener(ascoltatore);
        caselle.add(casella66);
        ImageButton casella67 = (ImageButton)findViewById(R.id.casella67);
        casella67.setOnClickListener(ascoltatore);
        caselle.add(casella67);
        ImageButton casella68 = (ImageButton)findViewById(R.id.casella68);
        casella68.setOnClickListener(ascoltatore);
        caselle.add(casella68);
        ImageButton casella69 = (ImageButton)findViewById(R.id.casella69);
        casella69.setOnClickListener(ascoltatore);
        caselle.add(casella69);
        ImageButton casella70 = (ImageButton)findViewById(R.id.casella70);
        casella70.setOnClickListener(ascoltatore);
        caselle.add(casella70);
        ImageButton casella71 = (ImageButton)findViewById(R.id.casella71);
        casella71.setOnClickListener(ascoltatore);
        caselle.add(casella71);
        ImageButton casella72 = (ImageButton)findViewById(R.id.casella72);
        casella72.setOnClickListener(ascoltatore);
        caselle.add(casella72);
        ImageButton casella73 = (ImageButton)findViewById(R.id.casella73);
        casella73.setOnClickListener(ascoltatore);
        caselle.add(casella73);
        ImageButton casella74 = (ImageButton)findViewById(R.id.casella74);
        casella74.setOnClickListener(ascoltatore);
        caselle.add(casella74);
        ImageButton casella75 = (ImageButton)findViewById(R.id.casella75);
        casella75.setOnClickListener(ascoltatore);
        caselle.add(casella75);
        ImageButton casella76 = (ImageButton)findViewById(R.id.casella76);
        casella76.setOnClickListener(ascoltatore);
        caselle.add(casella76);
        ImageButton casella77 = (ImageButton)findViewById(R.id.casella77);
        casella77.setOnClickListener(ascoltatore);
        caselle.add(casella77);
        ImageButton casella78 = (ImageButton)findViewById(R.id.casella78);
        casella78.setOnClickListener(ascoltatore);
        caselle.add(casella78);
        ImageButton casella79 = (ImageButton)findViewById(R.id.casella79);
        casella79.setOnClickListener(ascoltatore);
        caselle.add(casella79);
        ImageButton casella80 = (ImageButton)findViewById(R.id.casella80);
        casella80.setOnClickListener(ascoltatore);
        caselle.add(casella80);
        ImageButton casella81 = (ImageButton)findViewById(R.id.casella81);
        casella81.setOnClickListener(ascoltatore);
        caselle.add(casella81);
        ImageButton casella82 = (ImageButton)findViewById(R.id.casella82);
        casella82.setOnClickListener(ascoltatore);
        caselle.add(casella82);
        ImageButton casella83 = (ImageButton)findViewById(R.id.casella83);
        casella83.setOnClickListener(ascoltatore);
        caselle.add(casella83);
        ImageButton casella84 = (ImageButton)findViewById(R.id.casella84);
        casella84.setOnClickListener(ascoltatore);
        caselle.add(casella84);
        ImageButton casella85 = (ImageButton)findViewById(R.id.casella85);
        casella85.setOnClickListener(ascoltatore);
        caselle.add(casella85);
        ImageButton casella86 = (ImageButton)findViewById(R.id.casella86);
        casella86.setOnClickListener(ascoltatore);
        caselle.add(casella86);
        ImageButton casella87 = (ImageButton)findViewById(R.id.casella87);
        casella87.setOnClickListener(ascoltatore);
        caselle.add(casella87);
        ImageButton casella88 = (ImageButton)findViewById(R.id.casella88);
        casella88.setOnClickListener(ascoltatore);
        caselle.add(casella88);
        ImageButton casella89 = (ImageButton)findViewById(R.id.casella89);
        casella89.setOnClickListener(ascoltatore);
        caselle.add(casella89);
        cinquina.setOnClickListener(ascoltatore);
        decima.setOnClickListener(ascoltatore);
        tombola.setOnClickListener(ascoltatore);
        piu.setOnClickListener(ascoltatore);
        meno.setOnClickListener(ascoltatore);
        annulla.setOnClickListener(ascoltatore);
}

    @Override
    protected void onResume() {super.onResume();}

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        ImageButton casella_ultimo = (ImageButton) findViewById(R.id.casella_ultimo_numero);
        ultimo.setTextSize((casella_ultimo.getWidth()/2f)/2.65f);

        ImageButton casella_penultimo = (ImageButton) findViewById(R.id.casella_penultimo_numero);
        penultimo.setTextSize((casella_penultimo.getWidth()/2f)/2.65f);

        ImageButton casella_terzultimo = (ImageButton) findViewById(R.id.casella_terzultimo_numero);
        terzultimo.setTextSize((casella_terzultimo.getWidth()/2f)/2.65f);

        ImageButton casella_giro = (ImageButton) findViewById(R.id.casella_giro);
        giro.setTextSize((casella_giro.getWidth()/2f)/2.65f);

        Button casella0 = (Button) findViewById(R.id.casella0);
       /* LayerDrawable layerDrawable = (LayerDrawable) getResources().getDrawable(R.drawable.casella_left_top);
        GradientDrawable gradientDrawable = (GradientDrawable) layerDrawable.findDrawableByLayerId(R.id.bordo_sinistro);
        gradientDrawable.setShape();*/
        Log.i("WIDTH BUTTON",Integer.toString(casella0.getWidth()));
        casella0.setTextSize((casella0.getWidth()/2f)/2.65f);
        Float width = (casella0.getWidth()/2f)/2.65f;
        TextView testo1 = (TextView)findViewById(R.id.testo1);
        testo1.setTextSize(width);
        TextView testo2 = (TextView)findViewById(R.id.testo2);
        testo2.setTextSize(width);
        TextView testo3 = (TextView)findViewById(R.id.testo3);
        testo3.setTextSize(width);
        TextView testo4 = (TextView)findViewById(R.id.testo4);
        testo4.setTextSize(width);
        TextView testo5 = (TextView)findViewById(R.id.testo5);
        testo5.setTextSize(width);
        TextView testo6 = (TextView)findViewById(R.id.testo6);
        testo6.setTextSize(width);
        TextView testo7 = (TextView)findViewById(R.id.testo7);
        testo7.setTextSize(width);
        TextView testo8 = (TextView)findViewById(R.id.testo8);
        testo8.setTextSize(width);
        TextView testo9 = (TextView)findViewById(R.id.testo9);
        testo9.setTextSize(width);
        TextView testo10 = (TextView)findViewById(R.id.testo10);
        testo10.setTextSize(width);
        TextView testo11 = (TextView)findViewById(R.id.testo11);
        testo11.setTextSize(width);
        TextView testo12 = (TextView)findViewById(R.id.testo12);
        testo12.setTextSize(width);
        TextView testo13 = (TextView)findViewById(R.id.testo13);
        testo13.setTextSize(width);
        TextView testo14 = (TextView)findViewById(R.id.testo14);
        testo14.setTextSize(width);
        TextView testo15 = (TextView)findViewById(R.id.testo15);
        testo15.setTextSize(width);
        TextView testo16 = (TextView)findViewById(R.id.testo16);
        testo16.setTextSize(width);
        TextView testo17 = (TextView)findViewById(R.id.testo17);
        testo17.setTextSize(width);
        TextView testo18 = (TextView)findViewById(R.id.testo18);
        testo18.setTextSize(width);
        TextView testo19 = (TextView)findViewById(R.id.testo19);
        testo19.setTextSize(width);
        TextView testo20 = (TextView)findViewById(R.id.testo20);
        testo20.setTextSize(width);
        TextView testo21 = (TextView)findViewById(R.id.testo21);
        testo21.setTextSize(width);
        TextView testo22 = (TextView)findViewById(R.id.testo22);
        testo22.setTextSize(width);
        TextView testo23 = (TextView)findViewById(R.id.testo23);
        testo23.setTextSize(width);
        TextView testo24 = (TextView)findViewById(R.id.testo24);
        testo24.setTextSize(width);
        TextView testo25 = (TextView)findViewById(R.id.testo25);
        testo25.setTextSize(width);
        TextView testo26 = (TextView)findViewById(R.id.testo26);
        testo26.setTextSize(width);
        TextView testo27 = (TextView)findViewById(R.id.testo27);
        testo27.setTextSize(width);
        TextView testo28 = (TextView)findViewById(R.id.testo28);
        testo28.setTextSize(width);
        TextView testo29 = (TextView)findViewById(R.id.testo29);
        testo29.setTextSize(width);
        TextView testo30 = (TextView)findViewById(R.id.testo30);
        testo30.setTextSize(width);
        TextView testo31 = (TextView)findViewById(R.id.testo31);
        testo31.setTextSize(width);
        TextView testo32 = (TextView)findViewById(R.id.testo32);
        testo32.setTextSize(width);
        TextView testo33 = (TextView)findViewById(R.id.testo33);
        testo33.setTextSize(width);
        TextView testo34 = (TextView)findViewById(R.id.testo34);
        testo34.setTextSize(width);
        TextView testo35 = (TextView)findViewById(R.id.testo35);
        testo35.setTextSize(width);
        TextView testo36 = (TextView)findViewById(R.id.testo36);
        testo36.setTextSize(width);
        TextView testo37 = (TextView)findViewById(R.id.testo37);
        testo37.setTextSize(width);
        TextView testo38 = (TextView)findViewById(R.id.testo38);
        testo38.setTextSize(width);
        TextView testo39 = (TextView)findViewById(R.id.testo39);
        testo39.setTextSize(width);
        TextView testo40 = (TextView)findViewById(R.id.testo40);
        testo40.setTextSize(width);
        TextView testo41 = (TextView)findViewById(R.id.testo41);
        testo41.setTextSize(width);
        TextView testo42 = (TextView)findViewById(R.id.testo42);
        testo42.setTextSize(width);
        TextView testo43 = (TextView)findViewById(R.id.testo43);
        testo43.setTextSize(width);
        TextView testo44 = (TextView)findViewById(R.id.testo44);
        testo44.setTextSize(width);
        TextView testo45 = (TextView)findViewById(R.id.testo45);
        testo45.setTextSize(width);
        TextView testo46 = (TextView)findViewById(R.id.testo46);
        testo46.setTextSize(width);
        TextView testo47 = (TextView)findViewById(R.id.testo47);
        testo47.setTextSize(width);
        TextView testo48 = (TextView)findViewById(R.id.testo48);
        testo48.setTextSize(width);
        TextView testo49 = (TextView)findViewById(R.id.testo49);
        testo49.setTextSize(width);
        TextView testo50 = (TextView)findViewById(R.id.testo50);
        testo50.setTextSize(width);
        TextView testo51 = (TextView)findViewById(R.id.testo51);
        testo51.setTextSize(width);
        TextView testo52 = (TextView)findViewById(R.id.testo52);
        testo52.setTextSize(width);
        TextView testo53 = (TextView)findViewById(R.id.testo53);
        testo53.setTextSize(width);
        TextView testo54 = (TextView)findViewById(R.id.testo54);
        testo54.setTextSize(width);
        TextView testo55 = (TextView)findViewById(R.id.testo55);
        testo55.setTextSize(width);
        TextView testo56 = (TextView)findViewById(R.id.testo56);
        testo56.setTextSize(width);
        TextView testo57 = (TextView)findViewById(R.id.testo57);
        testo57.setTextSize(width);
        TextView testo58 = (TextView)findViewById(R.id.testo58);
        testo58.setTextSize(width);
        TextView testo59 = (TextView)findViewById(R.id.testo59);
        testo59.setTextSize(width);
        TextView testo60 = (TextView)findViewById(R.id.testo60);
        testo60.setTextSize(width);
        TextView testo61 = (TextView)findViewById(R.id.testo61);
        testo61.setTextSize(width);
        TextView testo62 = (TextView)findViewById(R.id.testo62);
        testo62.setTextSize(width);
        TextView testo63 = (TextView)findViewById(R.id.testo63);
        testo63.setTextSize(width);
        TextView testo64 = (TextView)findViewById(R.id.testo64);
        testo64.setTextSize(width);
        TextView testo65 = (TextView)findViewById(R.id.testo65);
        testo65.setTextSize(width);
        TextView testo66 = (TextView)findViewById(R.id.testo66);
        testo66.setTextSize(width);
        TextView testo67 = (TextView)findViewById(R.id.testo67);
        testo67.setTextSize(width);
        TextView testo68 = (TextView)findViewById(R.id.testo68);
        testo68.setTextSize(width);
        TextView testo69 = (TextView)findViewById(R.id.testo69);
        testo69.setTextSize(width);
        TextView testo70 = (TextView)findViewById(R.id.testo70);
        testo70.setTextSize(width);
        TextView testo71 = (TextView)findViewById(R.id.testo71);
        testo71.setTextSize(width);
        TextView testo72 = (TextView)findViewById(R.id.testo72);
        testo72.setTextSize(width);
        TextView testo73 = (TextView)findViewById(R.id.testo73);
        testo73.setTextSize(width);
        TextView testo74 = (TextView)findViewById(R.id.testo74);
        testo74.setTextSize(width);
        TextView testo75 = (TextView)findViewById(R.id.testo75);
        testo75.setTextSize(width);
        TextView testo76 = (TextView)findViewById(R.id.testo76);
        testo76.setTextSize(width);
        TextView testo77 = (TextView)findViewById(R.id.testo77);
        testo77.setTextSize(width);
        TextView testo78 = (TextView)findViewById(R.id.testo78);
        testo78.setTextSize(width);
        TextView testo79 = (TextView)findViewById(R.id.testo79);
        testo79.setTextSize(width);
        TextView testo80 = (TextView)findViewById(R.id.testo80);
        testo80.setTextSize(width);
        TextView testo81 = (TextView)findViewById(R.id.testo81);
        testo81.setTextSize(width);
        TextView testo82 = (TextView)findViewById(R.id.testo82);
        testo82.setTextSize(width);
        TextView testo83 = (TextView)findViewById(R.id.testo83);
        testo83.setTextSize(width);
        TextView testo84 = (TextView)findViewById(R.id.testo84);
        testo84.setTextSize(width);
        TextView testo85 = (TextView)findViewById(R.id.testo85);
        testo85.setTextSize(width);
        TextView testo86 = (TextView)findViewById(R.id.testo86);
        testo86.setTextSize(width);
        TextView testo87 = (TextView)findViewById(R.id.testo87);
        testo87.setTextSize(width);
        TextView testo88 = (TextView)findViewById(R.id.testo88);
        testo88.setTextSize(width);
        TextView testo89 = (TextView)findViewById(R.id.testo89);
        testo89.setTextSize(width);
    }
}
